language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database test_bucketlist_db;' -U postgres

script:
  - nosetests --with-coverage

after_success:
    - coveralls

cache: pip

notifications:
  email: false
re: change