"""empty message

Revision ID: 376fcb0bc9f1
Revises: 7afccf73775e
Create Date: 2017-05-22 09:28:47.527523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376fcb0bc9f1'
down_revision = '7afccf73775e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
