"""empty message

Revision ID: 4d87212407d3
Revises: 84e2600ad45e
Create Date: 2017-05-23 19:43:54.296093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d87212407d3'
down_revision = '84e2600ad45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlist', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('bucketlistitems', 'bucketlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bucketlistitems', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bucketlistitems', 'item_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlistitems', 'item_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bucketlistitems', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bucketlistitems', 'bucketlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bucketlist', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
