"""empty message

Revision ID: 5c0ad5170348
Revises: 74f2b731edd4
Create Date: 2017-05-23 15:49:55.527677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0ad5170348'
down_revision = '74f2b731edd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlistitems', sa.Column('item_name', sa.String(length=255), nullable=True))
    op.drop_column('bucketlistitems', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlistitems', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('bucketlistitems', 'item_name')
    # ### end Alembic commands ###
