"""empty message

Revision ID: ac00794229c7
Revises: 4d87212407d3
Create Date: 2017-05-24 09:03:59.175539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac00794229c7'
down_revision = '4d87212407d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlistitems', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlistitems', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
