"""empty message

Revision ID: adb726d6b406
Revises: ac00794229c7
Create Date: 2017-05-24 09:09:01.013585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb726d6b406'
down_revision = 'ac00794229c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlistitems', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlistitems', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
