"""empty message

Revision ID: b79926674d77
Revises: e9303d51b361
Create Date: 2017-05-21 12:57:07.014485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79926674d77'
down_revision = 'e9303d51b361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlist', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('bucketlistitems', 'bucketlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bucketlistitems', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlistitems', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bucketlistitems', 'bucketlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bucketlist', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
